before_script:
  - wget $DOWNLOAD_DEV_LOCAL
  - mkdir -p local_jars/dev-local/
  - mv dev-local.jar local_jars/dev-local

test:
  image: clojure:openjdk-14-tools-deps-alpine
  script:
    - clojure -A:test
  artifacts:
    paths:
      - target/coverage/index.html
    expire_in: 1 day

lint:
  image: clojure:openjdk-14-tools-deps-alpine
  script:
    - clojure -A:clj-kondo --lint src
  allow_failure: true
  when: always

up-to-date?:
  image: clojure:openjdk-14-tools-deps-alpine
  script:
    - clojure -A:ancient
  allow_failure: true
  when: always
